swagger: '2.0'
info:
  title: Manufacturers API
  description: This is an API for managing manufacturers.
  termsOfService: https://drone.prototype.apievangelist.com/terms-of-service/
  contact:
    name: API Evangelist
    url: https://apievangelist.com
    email: info@apievangelist.com
  version: v1.1
host: drone.prototype.apievangelist.com
basePath: /apis
schemes:
- http
produces:
- application/json
paths:
  /manufacturers/:
    get:
      summary: Get Manufacturers
      description: Get Manufacturers
      operationId: getManufacturers
      responses:
        '200':
          description: Manufacturers Response
          schema:
            type: array
            items:
              $ref: "#/definitions/manufacturer"
      tags:
      - Manufacturers
definitions:
  manufacturer:
    properties:
      manufacturer-id:
        description: The uniqud id for the manufacturer.
        type: string
      name:
        description: The name of the manufacturer.
        type: string
      description:
        description: The description for the manufacturer.
        type: string
      country:
        description: The country of the manufacturer.
        type: string
    required:
      - id
