swagger: '2.0'
info:
  title: Developers API
  description: This is an API for managing developers part of the showcase.
  termsOfService: https://drone.prototype.apievangelist.com/terms-of-service/
  contact:
    name: API Evangelist
    url: https://apievangelist.com
    email: info@apievangelist.com
  version: v1.1
host: drone.prototype.apievangelist.com
basePath: /apis
schemes:
- http
produces:
- application/json
paths:
  /developers/:
    get:
      summary: Get developers
      description: Get Developers
      operationId: getDeveloper
      responses:
        '200':
          description: Developer Response
          schema:
            type: array
            items:
              $ref: "#/definitions/developer"
      tags:
      - Developer
definitions:
  developer:
    properties:
      developer_id:
        description: The unique developer id of the developer.
        type: string
      name:
        description: The name of the developer.
        type: string
      description:
        description: The make of the developer.
        type: string
      image:
        description: The model of the developer.
        type: string
      url:
        description: The description for the developer.
        type: string
      twitter:
        description: The image for the developer.
        type: string
      github:
        description: The image for the developer.
        type: string
    required:
      - developer_id
