swagger: '2.0'
info:
  title: Plans API
  description: This is an API for managing API access plans.
  termsOfService: https://drone.prototype.apievangelist.com/terms-of-service/
  contact:
    name: API Evangelist
    url: https://apievangelist.com
    email: info@apievangelist.com
  version: v1.1
host: drone.prototype.apievangelist.com
basePath: /apis
schemes:
- http
produces:
- application/json
paths:
  /plan/:
    get:
      summary: Get Plans
      description: Get Plans
      operationId: getPlan
      responses:
        '200':
          description: Plan Response
          schema:
            type: array
            items:
              $ref: "#/definitions/plan"
      tags:
      - Plan
definitions:
  plan:
    properties:
      plan_id:
        description: The id of the plan.
        type: string
      name:
        description: The name of the plan.
        type: string
      description:
        description: The make of the plan.
        type: string
    required:
      - plan_id
