swagger: '2.0'
info:
  title: Webhook API
  description: This is an API for managing webhook.
  termsOfService: https://drone.prototype.apievangelist.com/terms-of-service/
  contact:
    name: API Evangelist
    url: https://apievangelist.com
    email: info@apievangelist.com
  version: v1.1
host: drone.prototype.apievangelist.com
basePath: /apis
schemes:
- http
produces:
- application/json
paths:
  /webhook/:
    get:
      summary: Get Webhook
      description: Get Webhook
      operationId: getWebhook
      responses:
        '200':
          description: Webhook Response
          schema:
            type: array
            items:
              $ref: "#/definitions/webhook"
      tags:
      - Webhook
definitions:
  webhook:
    properties:
      webhook_id:
        description: The id for the webhook.
        type: string
      account_id:
        description: The account id for the webhook.
        type: string
      url:
        description: The url for the webhook.
        type: string
      status:
        description: The status of the webhook.
        type: string
    required:
      - webhook_id
