title:        Drone Prototype
description:  This is a prototype of a drone API.
url:          https://drone.prototype.apievangelist.com

version:      1.1.1

author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown
permalink:    pretty
pygments:     true
highlighter:  rouge

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md",".DS_Store"]

logo : https://s3.amazonaws.com/kinlane-productions/api-evangelist/api-evangelist-101.png

github_user: api-evangelist-prototypes
github_repo: drones
