swagger: '2.0'
info:
  title: Accounts API
  description: This is an API for managing API consumer accounts.
  termsOfService: https://drone.prototype.apievangelist.com/terms-of-service/
  contact:
    name: API Evangelist
    url: https://apievangelist.com
    email: info@apievangelist.com
  version: v1.1
host: drone.prototype.apievangelist.com
basePath: /apis
schemes:
- http
produces:
- application/json
paths:
  /accounts/:
    get:
      summary: Get Accounts
      description: Get Accounts
      operationId: getAccounts
      responses:
        '200':
          description: Accounts Response
          schema:
            type: array
            items:
              $ref: "#/definitions/account"
      tags:
      - Accounts
definitions:
  account:
    properties:
      account_id:
        description: The unique id for the account.
        type: string
      name:
        description: The name of the account.
        type: string
    required:
      - account_id
