swagger: '2.0'
info:
  title: Billing API
  description: This is an API for managing API consumer billing.
  termsOfService: https://drone.prototype.apievangelist.com/terms-of-service/
  contact:
    name: API Evangelist
    url: https://apievangelist.com
    email: info@apievangelist.com
  version: v1.1
host: drone.prototype.apievangelist.com
basePath: /apis
schemes:
- http
produces:
- application/json
paths:
  /billing/:
    get:
      summary: Get Billing
      description: Get Billing
      operationId: getBilling
      responses:
        '200':
          description: Billing Response
          schema:
            type: array
            items:
              $ref: "#/definitions/billing"
      tags:
      - Billing
definitions:
  billing:
    properties:
      billing_id:
        description: The unqiue id for the billing.
        type: string
      account_id:
        description: The account id for the billing.
        type: string
      month:
        description: The month of the billing.
        type: string
      amount:
        description: The amount of the billing.
        type: string
    required:
      - billing_id
