swagger: '2.0'
info:
  title: Messages API
  description: This is an API for managing AP consumer messages.
  termsOfService: https://drone.prototype.apievangelist.com/terms-of-service/
  contact:
    name: API Evangelist
    url: https://apievangelist.com
    email: info@apievangelist.com
  version: v1.1
host: drone.prototype.apievangelist.com
basePath: /apis
schemes:
- http
produces:
- application/json
paths:
  /message/:
    get:
      summary: Get Messages
      description: Get Messages
      operationId: getMessages
      responses:
        '200':
          description: Messages Response
          schema:
            type: array
            items:
              $ref: "#/definitions/message"
      tags:
      - Messages
definitions:
  message:
    properties:
      message_id:
        description: The unique id for the message.
        type: string
      title:
        description: The title of the message.
        type: string
      message:
        description: The body of the message.
        type: string
      date:
        description: The date of the message.
        type: string
      user_id:
        description: The user id for the message.
        type: string
    required:
      - message_id
