swagger: '2.0'
info:
  title: User API
  description: This is an API for managing users.
  termsOfService: https://drone.prototype.apievangelist.com/terms-of-service/
  contact:
    name: API Evangelist
    url: https://apievangelist.com
    email: info@apievangelist.com
  version: v1.1
host: drone.prototype.apievangelist.com
basePath: /apis
schemes:
- http
produces:
- application/json
paths:
  /user/:
    get:
      summary: Get User
      description: Get User
      operationId: getUser
      responses:
        '200':
          description: User Response
          schema:
            type: array
            items:
              $ref: "#/definitions/user"
      tags:
      - User
definitions:
  user:
    properties:
      user_id:
        description: The unique id of the user.
        type: string
      name:
        description: The name of the user.
        type: string
      email:
        description: The email address for the user.
        type: string
      description:
        description: The description of the user.
        type: string
      twitter:
        description: The twitter account for the user.
        type: string
      github:
        description: The github account for the user.
        type: string
      google:
        description: The google account for the user.
        type: string
    required:
      - user_id
