swagger: '2.0'
info:
  title: Flights API
  description: This is an API for managing flights.
  termsOfService: https://drone.prototype.apievangelist.com/terms-of-service/
  contact:
    name: API Evangelist
    url: https://apievangelist.com
    email: info@apievangelist.com
  version: v1.1
host: drone.prototype.apievangelist.com
basePath: /apis
schemes:
- http
produces:
- application/json
paths:
  /flights/:
    get:
      summary: Get Flights
      description: Get Flights
      operationId: getFlights
      responses:
        '200':
          description: Flights Response
          schema:
            type: array
            items:
              $ref: "#/definitions/flight"
      tags:
      - Flights
definitions:
  flight:
    properties:
      flight_id:
        description: The unique id for this flight.
        type: string
      pilot_id:
        description: The pilots unique id for this flight.
        type: string
      aircraft_id:
        description:  The aircraft unique id for this flight.
        type: string
      start_time:
        description: The start timestamp for the flight.
        type: string
      end_time:
        description: The end timestamp for the flight.
        type: string
    required:
      - flight_id
