swagger: '2.0'
info:
  title: Flight Entries API
  description: This is an API for working with flight entries.
  termsOfService: https://drone.prototype.apievangelist.com/terms-of-service/
  contact:
    name: API Evangelist
    url: https://apievangelist.com
    email: info@apievangelist.com
  version: v1.1
host: drone.prototype.apievangelist.com
basePath: /apis
schemes:
- http
produces:
- application/json
paths:
  /flight-entries/:
    get:
      summary: Get Flight Entry
      description: Get Flight Entry
      operationId: getFlightEntry
      responses:
        '200':
          description: Flight Entry Response
          schema:
            type: array
            items:
              $ref: "#/definitions/flight_entry"
      tags:
      - Flight Entries
definitions:
  flight_entry:
    properties:
      flight-entry-id:
        description: The unique id for the flight entry.
        type: string
      timestamp:
        description: The timestamp for the flight entry.
        type: string
      latitude:
        description: The latitude for the flight entry.
        type: string
      longitude:
        description: The longitude for the flight entry.
        type: string
      altitude:
        description: The altitude for the flight entry.
        type: string
    required:
      - id
