swagger: '2.0'
info:
  title: Storage API
  description: This is an API for managing storage across the platform.
  termsOfService: https://drone.prototype.apievangelist.com/terms-of-service/
  contact:
    name: API Evangelist
    url: https://apievangelist.com
    email: info@apievangelist.com
  version: v1.1
host: drone.prototype.apievangelist.com
basePath: /apis
schemes:
- http
produces:
- application/json
paths:
  /storage/:
    get:
      summary: Get Storage
      description: Get Storage
      operationId: getStorage
      responses:
        '200':
          description: Storage Response
          schema:
            type: array
            items:
              $ref: "#/definitions/storage"
      tags:
      - Storage
definitions:
  storage:
    properties:
      storage_id:
        description: The unique id of the storage item.
        type: string
      name:
        description: The name of the storage item.
        type: string
      path:
        description: The path for the storage item.
        type: string
      size:
        description: The size of the storage item.
        type: string
      modified:
        description: The last time the item was modified.
        type: string
    required:
      - storage_id
