swagger: '2.0'
info:
  title: Usage API
  description: This is an API for acessing usage logs.
  termsOfService: https://drone.prototype.apievangelist.com/terms-of-service/
  contact:
    name: API Evangelist
    url: https://apievangelist.com
    email: info@apievangelist.com
  version: v1.1
host: drone.prototype.apievangelist.com
basePath: /apis
schemes:
- http
produces:
- application/json
paths:
  /usage/:
    get:
      summary: Get Usage
      description: Get Usage
      operationId: getUsage
      responses:
        '200':
          description: Usage Response
          schema:
            type: array
            items:
              $ref: "#/definitions/usage"
      tags:
      - Usage
definitions:
  usage:
    properties:
      usage_id:
        description: The unique id for the usage entry.
        type: string
      path:
        description: The path of what was used.
        type: string
      timestamp:
        description: The timestamp fro the usage.
        type: string
    required:
      - usage_id
