swagger: '2.0'
info:
  title: Flight Status API
  description: This is an API for accessing flight status.
  termsOfService: https://drone.prototype.apievangelist.com/terms-of-service/
  contact:
    name: API Evangelist
    url: https://apievangelist.com
    email: info@apievangelist.com
  version: v1.1
host: drone.prototype.apievangelist.com
basePath: /apis
schemes:
- http
produces:
- application/json
paths:
  /flight-status/:
    get:
      summary: Get Flight Status
      description: Get Flight Status
      operationId: getFlightStatus
      responses:
        '200':
          description: Flight Status Response
          schema:
            type: array
            items:
              $ref: "#/definitions/flight_status"
      tags:
      - Flight Status
definitions:
  flight_status:
    properties:
      flight-status-id:
        description: The unique id for the flight status.
        type: string
      timestamp:
        description: The timestamp for the flight status.
        type: string
      pilot-id:
        description: The pilots uniqud id for flight status.
        type: string
      aircraft-id:
        description: The unique aircraft id for this flight status.
        type: string
      status:
        description: The actual status for the flight.
        type: string
    required:
      - id
