swagger: '2.0'
info:
  title: Logging API
  description: This is an API for managing logging across systems.
  termsOfService: https://drone.prototype.apievangelist.com/terms-of-service/
  contact:
    name: API Evangelist
    url: https://apievangelist.com
    email: info@apievangelist.com
  version: v1.1
host: drone.prototype.apievangelist.com
basePath: /apis
schemes:
- http
produces:
- application/json
paths:
  /logging/:
    get:
      summary: Get Logging
      description: Get Logging
      operationId: getLogging
      responses:
        '200':
          description: Logging Response
          schema:
            type: array
            items:
              $ref: "#/definitions/logging"
      tags:
      - Logging
definitions:
  logging:
    properties:
      logging_id:
        description: The id of the logging.
        type: string
      event:
        description: The name of the logging.
        type: string
      timestamp:
        description: The make of the logging.
        type: string
    required:
      - logging_id
